USE vk;

DROP TABLE IF EXISTS Commentary;
DROP TABLE IF EXISTS Wall;
DROP TABLE IF EXISTS Post;

CREATE TABLE Post(
	ID SERIAL PRIMARY KEY,
	Body TEXT,
	AuthorUserId BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (AuthorUserId) REFERENCES Users (ID),
	CONSTRAINT fk_AuthorUserId_Users_Id FOREIGN KEY (AuthorUserId) REFERENCES Users (ID)
);

CREATE TABLE Commentary(
	ID SERIAL PRIMARY KEY,
	ParentCommentaryId BIGINT UNSIGNED,
	PostId BIGINT UNSIGNED NOT NULL,
	Body TEXT CHECK (Body <> '' AND Body IS NOT NULL),
	FOREIGN KEY (ParentCommentaryId) REFERENCES Commentary (ID),
	CONSTRAINT fk_ParentCommentaryId_Commentary_Id FOREIGN KEY (ParentCommentaryId) REFERENCES Commentary (ID),
	FOREIGN KEY (PostId) REFERENCES Post (ID),
	CONSTRAINT fk_Commentary_PostID FOREIGN KEY (PostId) REFERENCES Post (ID)
);

CREATE TABLE Wall(
	ID SERIAL PRIMARY KEY,
	PostId BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (PostId) REFERENCES Post (ID),
	CONSTRAINT fk_Wall_PostId FOREIGN KEY (PostId) REFERENCES Post (ID)
);
